// Per-repo central context, plus per-session notes, plus a programmatic
// transcript archive that's shared across all worktrees of the same repo.
// Inspired by clanky's `AGENTS.md` + `.clanky-planning` pattern: nothing
// magical — the agent reads/writes files in cwd; we make sure the right
// files exist at the right paths, the AGENTS.md tells the agent where to
// look and what to write back, AND MinionHQ programmatically tees every
// session's PTY output into a searchable per-repo dir so context is
// captured even when the agent doesn't think to write it down.
//
// Layout:
//
//   ~/.minionhq/repos/<key>/
//     meta.json          { realPath, slug, createdAt, updatedAt }
//     context/           ← THE shared central context for that repo
//       README.md        (auto-created on first init; explains the tier)
//       journal.md       (auto-created; agent appends progress entries here)
//       *.md             (durable repo facts: architecture, conventions, gotchas)
//     transcripts/       ← MinionHQ writes per-session PTY logs here automatically
//       <sessionId>.log  (raw PTY bytes, append-only)
//       INDEX.md         (auto-maintained: session id ↔ branch ↔ started ↔ status)
//
//   <worktree>/.minionhq/
//     repo-context/      → symlink → ~/.minionhq/repos/<key>/context/
//     transcripts/       → symlink → ~/.minionhq/repos/<key>/transcripts/
//     notes/             ← session-only scratch (git-ignored)
//     AGENTS.md          ← generated; tells Copilot where to read AND write
//     .gitignore         ← ignores this whole dir so the agent's branch stays clean

import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  realpathSync,
  statSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { join, basename, resolve } from 'node:path';
import { REPOS_DIR, ensureDirs } from './paths.js';

const README_TEMPLATE = `# Repo context

This directory holds **central context shared across every \`minionhq\` session running on this repo, on any branch, in any worktree**.

- Edit files here freely. All running sessions for this repo will see your changes on the next read.
- These files are NOT inside the repo itself, so they don't pollute branches and they don't get committed.
- Filename convention: short, focused topics (e.g. \`architecture.md\`, \`conventions.md\`, \`gotchas.md\`).

You can also drop a \`<repo>/context/\` directory inside the repo and it will be referenced too — useful for context that travels with the code.
`;

const JOURNAL_HEADER = `# Repo journal

Append-only log of significant work done across all MinionHQ sessions on
this repo. Agents are instructed to add a short entry here when they finish
a non-trivial chunk of work or learn something durable about the repo.

Format per entry:

    ## <ISO timestamp> — <branch> — <session-short-id>
    <2-5 lines: what was done, what was learned, what's next>

`;

const AGENTS_TEMPLATE = (opts: {
  branch: string;
  repoPath: string;
  hasInRepoContext: boolean;
}) => `# AGENTS.md (auto-generated by MinionHQ)

You are operating in a git worktree on branch **\`${opts.branch}\`** of repo **\`${opts.repoPath}\`**.

## Shared context for this repo (READ THIS FIRST)

Other MinionHQ sessions are (or have been) working on this same repo, possibly
on different branches in parallel. Their shared context is mounted right here
inside your worktree:

- \`./.minionhq/repo-context/\` — curated notes, conventions, architecture,
  gotchas. Read \`README.md\` and skim all \`*.md\` files here before doing
  significant work. Especially read \`journal.md\` — it's the running log of
  what other sessions have done.
- \`./.minionhq/transcripts/\` — raw PTY transcripts of every prior + concurrent
  session on this repo, one \`<sessionId>.log\` per session, plus \`INDEX.md\`
  listing them. To find what other sessions did about a topic:
  \`grep -li "topic" ./.minionhq/transcripts/*.log\` then read the matches.
${opts.hasInRepoContext ? `- \`${opts.repoPath}/context/\` — in-repo context that travels with the code.
  Read if relevant.
` : ''}- \`./.minionhq/notes/\` — scratch space for THIS session only (git-ignored).

## Writing back to shared context (IMPORTANT — do this proactively)

Whenever you do non-trivial work or learn something the next session would
benefit from, **write it down** in the appropriate place. Don't ask first —
just write it; the user can curate later.

- **Significant progress / learnings about this repo** → append a dated entry
  to \`./.minionhq/repo-context/journal.md\`. Keep entries short (2–5 lines).
  Example:
      ## 2025-01-15T10:30:00Z — ${opts.branch} — abcd1234
      Added auth middleware in src/auth. JWT verify happens in
      requireAuth(). Token refresh isn't wired yet — see TODO at line 42.
- **Durable repo facts** (architecture decisions, build quirks, conventions)
  → create or update a topic-specific file in \`./.minionhq/repo-context/\`
  (e.g. \`architecture.md\`, \`build.md\`).
- **Ephemeral, just-for-this-task** → \`./.minionhq/notes/\`.

These directories are real (top-level ones are symlinked to the per-repo
store), so writes persist and are immediately visible to every other session.

## Session status (for resume)

Before ending any non-trivial response, update \`./.minionhq/status.md\` with:
- What you're currently working on and its state
- Status of plan items (done / in progress / blocked)
- Next steps when work resumes

This lets a future session (or you, after compaction) pick up where you left off.

## Working in this worktree

- The whole \`./.minionhq/\` directory is git-ignored — write freely.
- The transcripts directory is MinionHQ's, not yours — read it but don't write to it.
- Treat the journal and curated notes as durable; keep entries focused.
`;

const GITIGNORE_CONTENT = `# managed by minionhq
# everything in this directory is local-only (notes, symlinks, AGENTS.md)
*
`;

export interface RepoContextInfo {
  key: string;
  realPath: string;
  centralDir: string;       // ~/.minionhq/repos/<key>/context
  transcriptsDir: string;   // ~/.minionhq/repos/<key>/transcripts
  metaPath: string;
}

function repoKey(realPath: string): string {
  const hash = createHash('sha1').update(realPath).digest('hex').slice(0, 10);
  const slug = basename(realPath).toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 30);
  return `${slug || 'repo'}-${hash}`;
}

export function ensureRepoContext(realPath: string): RepoContextInfo {
  ensureDirs();
  // Canonicalize so /tmp/X and /private/tmp/X resolve to the same repo key on macOS,
  // and so symlinked repo paths don't fragment central context.
  let abs: string;
  try {
    abs = realpathSync(resolve(realPath));
  } catch {
    abs = resolve(realPath);
  }
  const key = repoKey(abs);
  const dir = join(REPOS_DIR, key);
  const centralDir = join(dir, 'context');
  const transcriptsDir = join(dir, 'transcripts');
  const metaPath = join(dir, 'meta.json');

  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(centralDir)) {
    mkdirSync(centralDir, { recursive: true });
    writeFileSync(join(centralDir, 'README.md'), README_TEMPLATE);
  }
  // Seed journal.md so the agent has somewhere obvious to append.
  const journalPath = join(centralDir, 'journal.md');
  if (!existsSync(journalPath)) writeFileSync(journalPath, JOURNAL_HEADER);
  if (!existsSync(transcriptsDir)) mkdirSync(transcriptsDir, { recursive: true });

  let meta: { realPath: string; slug: string; createdAt: number; updatedAt: number };
  if (existsSync(metaPath)) {
    try {
      meta = JSON.parse(readFileSync(metaPath, 'utf8'));
      meta.realPath = abs;
      meta.updatedAt = Date.now();
    } catch {
      meta = { realPath: abs, slug: basename(abs), createdAt: Date.now(), updatedAt: Date.now() };
    }
  } else {
    meta = { realPath: abs, slug: basename(abs), createdAt: Date.now(), updatedAt: Date.now() };
  }
  writeFileSync(metaPath, JSON.stringify(meta, null, 2));

  return { key, realPath: abs, centralDir, transcriptsDir, metaPath };
}

/**
 * Resolve the per-repo transcripts directory for a given repo path.
 * Used by the logging layer to tee PTY output into a searchable per-repo
 * archive. Idempotent and cheap (just ensures dirs).
 */
export function getRepoTranscriptInfo(repoRealPath: string): { key: string; transcriptsDir: string } {
  const info = ensureRepoContext(repoRealPath);
  return { key: info.key, transcriptsDir: info.transcriptsDir };
}

/**
 * Append a single line to the per-repo transcripts INDEX.md so a human (or
 * another agent) can quickly see which transcripts exist and what they are.
 * Idempotent-ish: appends, doesn't deduplicate (each call should be made once
 * per session start).
 */
export function appendTranscriptIndex(opts: {
  repoRealPath: string;
  sessionId: string;
  branch: string;
  startedAt: number;
}): void {
  const { transcriptsDir } = getRepoTranscriptInfo(opts.repoRealPath);
  const indexPath = join(transcriptsDir, 'INDEX.md');
  const header = `# Transcript index\n\nOne entry per session. Each session's raw PTY output is in \`<sessionId>.log\`.\n\n`;
  if (!existsSync(indexPath)) writeFileSync(indexPath, header);
  const iso = new Date(opts.startedAt).toISOString();
  const short = opts.sessionId.slice(0, 8);
  const line = `- ${iso} — \`${short}\` (${opts.sessionId}) — branch \`${opts.branch}\`\n`;
  try {
    const cur = readFileSync(indexPath, 'utf8');
    if (cur.includes(opts.sessionId)) return; // dedupe on resume
    writeFileSync(indexPath, cur + line);
  } catch {
    writeFileSync(indexPath, header + line);
  }
}

/**
 * Set up `<worktree>/.minionhq/` with symlinks to per-repo central context
 * and transcripts, an empty `notes/` dir, an `AGENTS.md`, and a `.gitignore`
 * that hides the whole directory from git. Idempotent — safe to call on
 * existing worktrees.
 */
export function setupWorktreeContext(opts: {
  worktreePath: string;
  repoRealPath: string;
  branch: string;
}): { agentsPath: string; centralDir: string; transcriptsDir: string; repoKey: string } {
  const info = ensureRepoContext(opts.repoRealPath);
  const ctxRoot = join(opts.worktreePath, '.minionhq');
  if (!existsSync(ctxRoot)) mkdirSync(ctxRoot, { recursive: true });

  // Helper: idempotently symlink `target` into `linkPath`. If a non-symlink
  // exists at linkPath we leave it alone (might be user content).
  const ensureSymlink = (linkPath: string, target: string) => {
    let needCreate = true;
    try {
      const lst = lstatSync(linkPath);
      if (lst.isSymbolicLink()) {
        const cur = readlinkSync(linkPath);
        if (resolve(cur) === resolve(target)) {
          needCreate = false;
        } else {
          unlinkSync(linkPath);
        }
      } else {
        needCreate = false;
      }
    } catch {
      needCreate = true;
    }
    if (needCreate) {
      try { symlinkSync(target, linkPath, 'dir'); } catch { /* ignore */ }
    }
  };

  ensureSymlink(join(ctxRoot, 'repo-context'), info.centralDir);
  ensureSymlink(join(ctxRoot, 'transcripts'), info.transcriptsDir);

  // notes/
  const notesDir = join(ctxRoot, 'notes');
  if (!existsSync(notesDir)) mkdirSync(notesDir, { recursive: true });

  // .gitignore — hide the whole dir from the branch. Safe to overwrite.
  const giPath = join(ctxRoot, '.gitignore');
  writeFileSync(giPath, GITIGNORE_CONTENT);

  // AGENTS.md — discovered automatically by Copilot from cwd. Always
  // regenerate when we own it (marker at the top) so existing worktrees pick
  // up improved instructions on resume. If the user has hand-edited or
  // replaced it, leave it alone.
  const hasInRepoContext = existsSync(join(opts.repoRealPath, 'context'));
  const agentsPath = join(opts.worktreePath, 'AGENTS.md');
  const fresh = AGENTS_TEMPLATE({
    branch: opts.branch,
    repoPath: opts.repoRealPath,
    hasInRepoContext,
  });
  let shouldWriteAgents = true;
  if (existsSync(agentsPath)) {
    try {
      const cur = readFileSync(agentsPath, 'utf8');
      if (!cur.startsWith('# AGENTS.md (auto-generated by ')) {
        shouldWriteAgents = false;
      }
    } catch {
      shouldWriteAgents = true;
    }
  }
  if (shouldWriteAgents) writeFileSync(agentsPath, fresh);

  return {
    agentsPath,
    centralDir: info.centralDir,
    transcriptsDir: info.transcriptsDir,
    repoKey: info.key,
  };
}

export interface ContextFile {
  name: string;
  size: number;
  modified: number;
}

export function listRepoContextFiles(repoPath: string): ContextFile[] {
  const info = ensureRepoContext(repoPath);
  if (!existsSync(info.centralDir)) return [];
  return readdirSync(info.centralDir)
    .filter((n) => !n.startsWith('.'))
    .map((n) => {
      const p = join(info.centralDir, n);
      const s = statSync(p);
      return { name: n, size: s.size, modified: s.mtimeMs };
    });
}

export function readRepoContextFile(repoPath: string, name: string): string {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  return readFileSync(p, 'utf8');
}

export function writeRepoContextFile(repoPath: string, name: string, content: string): void {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  if (!/^[A-Za-z0-9._-]+\.md$/i.test(safe)) throw new Error('filename must match [A-Za-z0-9._-]+\\.md');
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  writeFileSync(p, content);
  // touch meta
  try {
    const meta = JSON.parse(readFileSync(info.metaPath, 'utf8'));
    meta.updatedAt = Date.now();
    writeFileSync(info.metaPath, JSON.stringify(meta, null, 2));
  } catch { /* ignore */ }
}

export function deleteRepoContextFile(repoPath: string, name: string): void {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  if (safe.toLowerCase() === 'readme.md') return; // protect
  if (existsSync(p)) unlinkSync(p);
}
