// Per-repo central context, plus per-session notes.
//
// Layout:
//
//   ~/.minionhq/repos/<key>/
//     meta.json          { realPath, slug, createdAt, updatedAt }
//     context/           ← THE shared central context for that repo
//       README.md        (auto-created on first init; explains the tier)
//       *.md             (user-editable; shared across all branches/sessions on this repo)
//
//   <worktree>/.minionhq/
//     repo-context/      → symlink → ~/.minionhq/repos/<key>/context/
//     notes/             ← session-only scratch (git-ignored)
//     AGENTS.md          ← generated; tells Copilot where each tier lives
//     .gitignore         ← ignores this whole dir so the agent's branch stays clean

import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  realpathSync,
  statSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { join, basename, resolve } from 'node:path';
import { REPOS_DIR, ensureDirs } from './paths.js';

const README_TEMPLATE = `# Repo context

This directory holds **central context shared across every \`minionhq\` session running on this repo, on any branch**.

- Edit files here freely. All running sessions for this repo will see your changes on the next read.
- These files are NOT inside the repo itself, so they don't pollute branches and they don't get committed.
- Filename convention: short, focused topics (e.g. \`architecture.md\`, \`conventions.md\`, \`gotchas.md\`).

You can also drop a \`<repo>/context/\` directory inside the repo and it will be referenced too — useful for context that travels with the code.
`;

const AGENTS_TEMPLATE = (opts: {
  branch: string;
  repoPath: string;
  hasInRepoContext: boolean;
}) => `# AGENTS.md (auto-generated by minionhq)

You are operating in a git worktree on branch **\`${opts.branch}\`** of repo **\`${opts.repoPath}\`**.

## Context tiers (read these before significant work)

1. **Central repo context** — \`./.minionhq/repo-context/\`
   Shared across all minionhq sessions on this repo (any branch). Read these first; they're the most authoritative source.

${opts.hasInRepoContext ? `2. **In-repo context** — \`${opts.repoPath}/context/\`
   Context that lives in the repo itself and travels with branches. Read if relevant to your task.

3. **Session notes** — \`./.minionhq/notes/\`
   Scratch space for THIS session only. Git-ignored. Drop intermediate findings here.
` : `2. **Session notes** — \`./.minionhq/notes/\`
   Scratch space for THIS session only. Git-ignored. Drop intermediate findings here.
`}

## Working in this worktree

- The whole \`./.minionhq/\` directory is git-ignored — feel free to write notes there without polluting the branch.
- When you discover something worth remembering across sessions, ask the user whether to promote your note from \`notes/\` into \`repo-context/\`.
`;

const GITIGNORE_CONTENT = `# managed by minionhq
# everything in this directory is local-only (notes, symlinks, AGENTS.md)
*
`;

export interface RepoContextInfo {
  key: string;
  realPath: string;
  centralDir: string;     // ~/.minionhq/repos/<key>/context
  metaPath: string;
}

function repoKey(realPath: string): string {
  const hash = createHash('sha1').update(realPath).digest('hex').slice(0, 10);
  const slug = basename(realPath).toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 30);
  return `${slug || 'repo'}-${hash}`;
}

export function ensureRepoContext(realPath: string): RepoContextInfo {
  ensureDirs();
  // Canonicalize so /tmp/X and /private/tmp/X resolve to the same repo key on macOS,
  // and so symlinked repo paths don't fragment central context.
  let abs: string;
  try {
    abs = realpathSync(resolve(realPath));
  } catch {
    abs = resolve(realPath);
  }
  const key = repoKey(abs);
  const dir = join(REPOS_DIR, key);
  const centralDir = join(dir, 'context');
  const metaPath = join(dir, 'meta.json');

  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(centralDir)) {
    mkdirSync(centralDir, { recursive: true });
    writeFileSync(join(centralDir, 'README.md'), README_TEMPLATE);
  }

  let meta: { realPath: string; slug: string; createdAt: number; updatedAt: number };
  if (existsSync(metaPath)) {
    try {
      meta = JSON.parse(readFileSync(metaPath, 'utf8'));
      meta.realPath = abs;
      meta.updatedAt = Date.now();
    } catch {
      meta = { realPath: abs, slug: basename(abs), createdAt: Date.now(), updatedAt: Date.now() };
    }
  } else {
    meta = { realPath: abs, slug: basename(abs), createdAt: Date.now(), updatedAt: Date.now() };
  }
  writeFileSync(metaPath, JSON.stringify(meta, null, 2));

  return { key, realPath: abs, centralDir, metaPath };
}

/**
 * Set up `<worktree>/.minionhq/` with the symlink to central context, an
 * empty `notes/` dir, an `AGENTS.md`, and a `.gitignore` that hides the whole
 * directory from git. Idempotent — safe to call on existing worktrees.
 */
export function setupWorktreeContext(opts: {
  worktreePath: string;
  repoRealPath: string;
  branch: string;
}): { agentsPath: string; centralDir: string } {
  const info = ensureRepoContext(opts.repoRealPath);
  const ctxRoot = join(opts.worktreePath, '.minionhq');
  if (!existsSync(ctxRoot)) mkdirSync(ctxRoot, { recursive: true });

  // Symlink central context in (replace if stale)
  const linkPath = join(ctxRoot, 'repo-context');
  let needCreate = true;
  try {
    const lst = lstatSync(linkPath);
    if (lst.isSymbolicLink()) {
      const target = readlinkSync(linkPath);
      if (resolve(target) === resolve(info.centralDir)) {
        needCreate = false;
      } else {
        unlinkSync(linkPath);
      }
    } else {
      // Exists but isn't a symlink — user content? Leave it alone.
      needCreate = false;
    }
  } catch {
    needCreate = true;
  }
  if (needCreate) {
    try { symlinkSync(info.centralDir, linkPath, 'dir'); } catch { /* ignore */ }
  }

  // notes/
  const notesDir = join(ctxRoot, 'notes');
  if (!existsSync(notesDir)) mkdirSync(notesDir, { recursive: true });

  // .gitignore — hide the whole dir from the branch
  const giPath = join(ctxRoot, '.gitignore');
  if (!existsSync(giPath)) writeFileSync(giPath, GITIGNORE_CONTENT);

  // AGENTS.md — discovered automatically by Copilot from cwd
  const hasInRepoContext = existsSync(join(opts.repoRealPath, 'context'));
  const agentsPath = join(opts.worktreePath, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    writeFileSync(agentsPath, AGENTS_TEMPLATE({
      branch: opts.branch,
      repoPath: opts.repoRealPath,
      hasInRepoContext,
    }));
  }

  return { agentsPath, centralDir: info.centralDir };
}

export interface ContextFile {
  name: string;
  size: number;
  modified: number;
}

export function listRepoContextFiles(repoPath: string): ContextFile[] {
  const info = ensureRepoContext(repoPath);
  if (!existsSync(info.centralDir)) return [];
  return readdirSync(info.centralDir)
    .filter((n) => !n.startsWith('.'))
    .map((n) => {
      const p = join(info.centralDir, n);
      const s = statSync(p);
      return { name: n, size: s.size, modified: s.mtimeMs };
    });
}

export function readRepoContextFile(repoPath: string, name: string): string {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  return readFileSync(p, 'utf8');
}

export function writeRepoContextFile(repoPath: string, name: string, content: string): void {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  if (!/^[A-Za-z0-9._-]+\.md$/i.test(safe)) throw new Error('filename must match [A-Za-z0-9._-]+\\.md');
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  writeFileSync(p, content);
  // touch meta
  try {
    const meta = JSON.parse(readFileSync(info.metaPath, 'utf8'));
    meta.updatedAt = Date.now();
    writeFileSync(info.metaPath, JSON.stringify(meta, null, 2));
  } catch { /* ignore */ }
}

export function deleteRepoContextFile(repoPath: string, name: string): void {
  const info = ensureRepoContext(repoPath);
  const safe = basename(name);
  const p = join(info.centralDir, safe);
  if (!p.startsWith(info.centralDir)) throw new Error('invalid path');
  if (safe.toLowerCase() === 'readme.md') return; // protect
  if (existsSync(p)) unlinkSync(p);
}
